version: "2"
exclude_patterns:
- "config/"
- "**/node_modules/"
- "**/spec/"
- "**/__mocks__/"
- "**/__tests__/"
- "**/*.spec.jsx"
- "**/*.spec.js"
- "src/**/index.js"
- "src/**/navlinks.js"
- "src/registerServiceWorker.js"
- "src/redux/store/"
