
export default [
  {
    id: 'gfgdvfuhdjhfhgdf',
    type: 'App\\Notifications\\FellowStatus',
    notifiable_id: 5,
    data: {
      status: 'onTrack',
      level: 'D0B',
      message: 'Hi Ronald, you are on Track for this week',
      email: 'ronald.mutebi@andela.com',
    },
    read_at: null,
    created_at: '2018-11-01 14:34:03',
    updated_at: '2018-10-29 14:34:03',
  },
  {
    id: 'rtrgfgdvfuhdjhfhgdf',
    type: 'App\\Notifications\\FellowStatus',
    notifiable_id: 5,
    data: {
      status: 'oFFTrack',
      level: 'D0B',
      message: 'Hi Bilango, you are off Track for this week',
      email: 'bilango.fake@andela.com',
    },
    read_at: null,
    created_at: '2018-10-31 14:34:03',
    updated_at: '2018-10-31 14:34:03',
  },
  {
    id: 'fsrtrgfgdvfuhdjhfhgdf',
    type: 'App\\Notifications\\FellowStatus',
    notifiable_id: 5,
    data: {
      status: 'oFFTrack',
      level: 'D0B',
      message: 'Hi mac, you are off Track for this week',
      email: 'mac.pc@andela.com',
    },
    read_at: null,
    created_at: '2018-10-29 14:34:03',
    updated_at: '2018-10-29 14:34:03',
  },
  {
    id: 'gfgdvfuhdjhfhgdf',
    type: 'App\\Notifications\\FellowStatus',
    notifiable_id: 5,
    data: {
      status: 'onTrack',
      level: 'D0B',
      message: 'Hi Ronald, you are on Track for this week',
      email: 'ronald.mutebi@andela.com',
    },
    read_at: null,
    created_at: '2018-10-27 14:34:03',
    updated_at: '2018-10-29 14:34:03',
  },
  {
    id: 'gfgdvfuhdjhfhgdf',
    type: 'App\\Notifications\\FellowStatus',
    notifiable_id: 5,
    data: {
      status: 'onTrack',
      level: 'D0B',
      message: 'Hi Ronald, you are on Track for this week',
      email: 'ronald.mutebi@andela.com',
    },
    read_at: null,
    created_at: '2018-10-29 14:34:03',
    updated_at: '2018-10-29 14:34:03',
  },
];
