export const NEW_TEAM_MEMBER_REQUEST_REQUEST =
  'NEW_TEAM_MEMBER_REQUEST_REQUEST';
export const NEW_TEAM_MEMBER_REQUEST_SUCCESS =
  'NEW_TEAM_MEMBER_REQUEST_SUCCESS';
export const NEW_TEAM_MEMBER_REQUEST_FAILURE = 'FETCH_APPLICATIONS_FAILURE';
