const TranslatorTable = {
  'pre-pip': 'Pre-PIP only',
  'Pre-PIP only': 'pre-pip',
  pip: 'PIP only',
  'PIP only': 'pip',
  'D0B Apprenticeship': 'D0B',
  D0B: 'D0B Apprenticeship',
  'D0A Simulations': 'D0A',
  D0A: 'D0A Simulations',
  pulse: 'DevPulse',
  DevPulse: 'pulse',
  lms: 'LMS',
  LMS: 'lms',
  'All Levels': '',
  'Pre-PIP & PIP': '',
  'All Criteria': '',
  'All Projects': '',
  'All Products': '',
  'All Fellows': '',
  'All TTLs': '',
  'All LFs': '',
  'On Track': 'onTrack',
  'Off Track': 'Wk5',
  PIP: true,
  WATCH_TOWER_LF: 'LF',
  WATCH_TOWER_OPS: 'TTL/LF',
  WATCH_TOWER_TTL: 'TTL',
  WATCH_TOWER_EM: 'TTL',
  WATCH_TOWER_SL: 'LF'
};

export default TranslatorTable;
