export const FETCH_CADREVACANCIES_REQUEST = 'FETCH_VACANCIES_REQUEST';
export const FETCH_CADREVACANCIES_SUCCESS = 'FETCH_VACANCIES_SUCCESS';
export const FETCH_CADREVACANCIES_FAILURE = 'FETCH_VACANCIES_FAILURE';

export const CERTIFICATION_APPLICATION_REQUEST =
  'CERTIFICATION_APPLICATION_REQUEST,';
export const CERTIFICATION_APPLICATION_SUCCESS =
  'CERTIFICATION_APPLICATION_SUCCESS';
export const CERTIFICATION_APPLICATION_FAILURE =
  'CERTIFICATION_APPLICATION_FAILURE';

export const ROLE_APPLICATION_SUCCESS = 'ROLE_APPLICATION_SUCCESS';
export const ROLE_APPLICATION_FAILURE = 'ROLE_APPLICATION_FAILURE';
export const ROLE_APPLICATION_REQUEST = 'ROLE_APPLICATION_REQUEST';
