export const ADD_CERTIFICATION_REQUEST = 'ADD_CERTIFICATION_REQUEST';
export const ADD_CERTIFICATION_SUCCESS = 'ADD_CERTIFICATION_SUCCESS';
export const ADD_CERTIFICATION_FAILURE = 'ADD_CERTIFICATION_FAILURE';
