export const FETCH_CERTIFICATION_REQUEST = 'FETCH_CERTIFICATION_REQUEST';
export const FETCH_CERTIFICATION_SUCCESS = 'FETCH_CERTIFICATION_SUCCESS';
export const FETCH_CERTIFICATION_FAILURE = 'FETCH_CERTIFICATION_FAILURE';

export const DELETE_CERTIFICATION_REQUEST = 'DELETE_CERTIFICATION_REQUEST';
export const DELETE_CERTIFICATION_SUCCESS = 'DELETE_CERTIFICATION_SUCCESS';
export const DELETE_CERTIFICATION_FAILURE = 'DELETE_CERTIFICATION_FAILURE';

export const REMOVE_CERTIFICATION_ON_FOCUS = 'REMOVE_CERTIFICATION_ON_FOCUS';
export const SET_CERTIFICATION_ON_FOCUS = 'SET_CERTIFICATION_ON_FOCUS';

export const FETCH_CERTIFICATION_APPLICANTS_REQUEST =
  'FETCH_CERTIFICATION_APPLICANTS_REQUEST';
export const FETCH_CERTIFICATION_APPLICANTS_SUCCESS =
  'FETCH_CERTIFICATION_APPLICANTS_SUCCESS';
export const FETCH_CERTIFICATION_APPLICANTS_FAILURE =
  'FETCH_CERTIFICATION_APPLICANTS_FAILURE';

export const GET_CERTIFICATION_REQUEST = 'GET_CERTIFICATION_REQUEST';
export const GET_CERTIFICATION_SUCCESS = 'GET_CERTIFICATION_SUCCESS';
export const GET_CERTIFICATION_FAILURE = 'GET_CERTIFICATION_FAILURE';

export const GET_CERTIFIED_ENGINEERS_REQUEST =
  'GET_CERTIFIED_ENGINEERS_REQUEST';
export const GET_CERTIFIED_ENGINEERS_SUCCESS =
  'GET_CERTIFIED_ENGINEERS_SUCCESS';
export const GET_CERTIFIED_ENGINEERS_FAILURE =
  'GET_CERTIFIED_ENGINEERS_FAILURE';

export const UPDATE_CERTIFICATION = 'UPDATE_CERTIFICATION';
