export const FETCH_CERTIFICATION_REQUEST = 'FETCH_CERTIFICATION_REQUEST';
export const FETCH_CERTIFICATION_SUCCESS = 'FETCH_CERTIFICATION_SUCCESS';
export const FETCH_CERTIFICATION_FAILURE = 'FETCH_CERTIFICATION_FAILURE';

export const DELETE_CERTIFICATION_REQUEST = 'DELETE_CERTIFICATION_REQUEST';
export const DELETE_CERTIFICATION_SUCCESS = 'DELETE_CERTIFICATION_SUCCESS';
export const DELETE_CERTIFICATION_FAILURE = 'DELETE_CERTIFICATION_FAILURE';

export const REMOVE_CERTIFICATION_ON_FOCUS = 'REMOVE_CERTIFICATION_ON_FOCUS';
export const SET_CERTIFICATION_ON_FOCUS = 'SET_CERTIFICATION_ON_FOCUS';
