export const FETCH_CERTIFICATION_REQUEST = 'FETCH_CERTIFICATION_REQUEST';
export const FETCH_CERTIFICATION_SUCCESS = 'FETCH_CERTIFICATION_SUCCESS';
export const FETCH_CERTIFICATION_FAILURE = 'FETCH_CERTIFICATION_FAILURE';
