export const FETCH_PROJECT_ROLES_REQUEST = 'FETCH_PROJECT_ROLES_REQUEST';
export const FETCH_PROJECT_ROLES_SUCCESS = 'FETCH_PROJECT_ROLES_SUCCESS';
export const FETCH_PROJECT_ROLES_FAILURE = 'FETCH_PROJECT_ROLES_FAILURE';
export const CREATE_PROJECT_ROLE_REQUEST = 'CREATE_PROJECT_ROLES_REQUEST';
export const CREATE_PROJECT_ROLE_SUCCESS = 'CREATE_PROJECT_ROLES_SUCCESS';
export const CREATE_PROJECT_ROLE_FAILURE = 'CREATE_PROJECT_ROLES_FAILURE';
export const FETCH_ROLE_SKILLS_REQUEST = 'FETCH_ROLE_SKILLS_REQUEST';
export const FETCH_ROLE_SKILLS_SUCCESS = 'FETCH_ROLE_SKILLS_SUCCESS';
export const FETCH_ROLE_SKILLS_FAILURE = 'FETCH_ROLE_SKILLS_FAILURE';
export const SET_PROJECT_ROLE_DELETE_TARGET = 'SET_PROJECT_ROLE_DELETE_TARGET';
export const DELETE_PROJECT_ROLE = 'DELETE_PROJECT_ROLE';
export const DELETE_PROJECT_ROLE_FAILURE = 'DELETE_PROJECT_ROLE_FAILURE';

export const FETCH_SINGLE_ROLE_REQUEST = 'FETCH_SINGLE_ROLE_REQUEST';
export const FETCH_SINGLE_ROLE_SUCCESS = 'FETCH_SINGLE_ROLE_SUCCESS';
export const FETCH_SINGLE_ROLE_FAILURE = 'FETCH_SINGLE_ROLE_FAILURE';
