export const FETCH_CADRE_SUCCESS = 'FETCH_CADRE_SUCCESS';
export const FETCH_CADRE_REQUEST = 'FETCH_CADRE_REQUEST';
export const FETCH_CADRE_FAILURE = 'FETCH_CADRE_FAILURE';
export const ACTIVATE_CADRE_ENGINEER_ACCOUNT_SUCCESS =
  'ACTIVATE_CADRE_ENGINEER_ACCOUNT_SUCCESS';
export const ACTIVATE_CADRE_ENGINEER_ACCOUNT_REQUEST =
  'ACTIVATE_CADRE_ENGINEER_ACCOUNT_REQUEST';
export const ACTIVATE_CADRE_ENGINEER_ACCOUNT_FAILURE =
  'ACTIVATE_CADRE_ENGINEER_ACCOUNT_FAILURE';
