export const FETCH_PROJECT_ROLES_REQUEST = 'FETCH_PROJECT_ROLES_REQUEST';
export const FETCH_PROJECT_ROLES_SUCCESS = 'FETCH_PROJECT_ROLES_SUCCESS';
export const FETCH_PROJECT_ROLES_FAILURE = 'FETCH_PROJECT_ROLES_FAILURE';
