export const FETCH_CADREVACANCIES_REQUEST = 'FETCH_VACANCIES_REQUEST';
export const FETCH_CADREVACANCIES_SUCCESS = 'FETCH_VACANCIES_SUCCESS';
export const FETCH_CADREVACANCIES_FAILURE = 'FETCH_VACANCIES_FAILURE';
