export const GET_CERTIFICATION_REQUEST = 'GET_CERTIFICATION_REQUEST';
export const GET_CERTIFICATION_SUCCESS = 'GET_CERTIFICATION_SUCCESS';
export const GET_CERTIFICATION_FAILURE = 'GET_CERTIFICATION_FAILURE';
