export const CREATE_CERTIFICATION_VACANCY_REQUEST =
  'CREATE_CERTIFICATION_VACANCY_REQUEST';
export const CREATE_CERTIFICATION_VACANCY_SUCCESS =
  'CREATE_CERTIFICATION_VACANCY_SUCCESS ';
export const CREATE_CERTIFICATION_VACANCY_FAIL =
  'CREATE_CERTIFICATION_VACANCY_FAIL';

export const DELETE_CERTIFICATION_VACANCIES_REQUEST =
  'DELETE_CERTIFICATION_VACANCIES_REQUEST';
export const DELETE_CERTIFICATION_VACANCIES_SUCCESS =
  'DELETE_CERTIFICATION_VACANCIES_SUCCESS';
export const DELETE_CERTIFICATION_VACANCIES_FAILURE =
  'DELETE_CERTIFICATION_VACANCIES_FAILURE';
export const REMOVE_CERTIFICATION_VACANCIES_ON_FOCUS =
  'REMOVE_CERTIFICATION_VACANCIES_ON_FOCUS';
  
export const EDIT_CERTIFICATION_VACANCY_REQUEST =
  'EDIT_CERTIFICATION_VACANCY_REQUEST';
export const EDIT_CERTIFICATION_VACANCY_SUCCESS =
  'EDIT_CERTIFICATION_VACANCY_SUCCESS';
export const EDIT_CERTIFICATION_VACANCY_FAILURE =
  'EDIT_CERTIFICATION_VACANCY_FAILURE';

export const SET_CERTIFICATION_VACANCIES_ON_FOCUS =
  'SET_CERTIFICATION_VACANCIES_ON_FOCUS';
export const UPDATE_CERTIFICATION_VACANCY_ON_FOCUS =
  'UPDATE_CERTIFICATION_VACANCY_ON_FOCUS';
