export const CREATE_CERTIFICATION_VACANCY_REQUEST =
  'CREATE_CERTIFICATION_VACANCY_REQUEST';
export const CREATE_CERTIFICATION_VACANCY_SUCCESS =
  'CREATE_CERTIFICATION_VACANCY_SUCCESS ';
export const CREATE_CERTIFICATION_VACANCY_FAIL =
  'CREATE_CERTIFICATION_VACANCY_FAIL';

export const DELETE_CERTIFICATION_VACANCIES_REQUEST =
  'DELETE_CERTIFICATION_VACANCIES_REQUEST';
export const DELETE_CERTIFICATION_VACANCIES_SUCCESS =
  'DELETE_CERTIFICATION_VACANCIES_SUCCESS';
export const DELETE_CERTIFICATION_VACANCIES_FAILURE =
  'DELETE_CERTIFICATION_VACANCIES_FAILURE';
export const REMOVE_CERTIFICATION_VACANCIES_ON_FOCUS =
  'REMOVE_CERTIFICATION_VACANCIES_ON_FOCUS';
