export const CREATE_CERTIFICATION_VACANCY_REQUEST =
  'CREATE_CERTIFICATION_VACANCY_REQUEST';
export const CREATE_CERTIFICATION_VACANCY_SUCCESS =
  'CREATE_CERTIFICATION_VACANCY_SUCCESS ';
export const CREATE_CERTIFICATION_VACANCY_FAIL =
  'CREATE_CERTIFICATION_VACANCY_FAIL';
