export const LOAD_D1_FELLOW_PROFILE_DATA_REQUEST =
  'LOAD_D1_FELLOW_PROFILE_DATA_REQUEST,';
export const LOAD_D1_FELLOW_PROFILE_DATA_SUCCESS =
  'LOAD_D1_FELLOW_PROFILE_DATA_SUCCESS';
export const LOAD_D1_FELLOW_PROFILE_DATA_FAILURE =
  'LOAD_D1_FELLOW_PROFILE_DATA_FAILURE';
