export const LOAD_D1_FELLOW_PROFILE_DATA_REQUEST =
  'LOAD_D1_FELLOW_PROFILE_DATA_REQUEST,';
export const LOAD_D1_FELLOW_PROFILE_DATA_SUCCESS =
  'LOAD_D1_FELLOW_PROFILE_DATA_SUCCESS';
export const LOAD_D1_FELLOW_PROFILE_DATA_FAILURE =
  'LOAD_D1_FELLOW_PROFILE_DATA_FAILURE';

export const ACTIVATE_CADRE_ENGINEER_ACCOUNT_SUCCESS =
  'ACTIVATE_CADRE_ENGINEER_ACCOUNT_SUCCESS';
export const ACTIVATE_CADRE_ENGINEER_ACCOUNT_REQUEST =
  'ACTIVATE_CADRE_ENGINEER_ACCOUNT_REQUEST';
export const ACTIVATE_CADRE_ENGINEER_ACCOUNT_FAILURE =
  'ACTIVATE_CADRE_ENGINEER_ACCOUNT_FAILURE';
