export const LOAD_EM_SIMSLEADS_REQUEST = 'LOAD_EM_SIMSLEADS_REQUEST';
export const LOAD_EM_SIMSLEADS_SUCCESS = 'LOAD_EM_SIMSLEADS_SUCCESS';
export const LOAD_EM_SIMSLEADS_FAILURE = 'LOAD_EM_SIMSLEADS_FAILURE';
