export const LOAD_ENGINEERING_MANAGER_TTLS_REQUEST =
  'LOAD_ENGINEERING_MANAGER_TTLS_REQUEST';
export const LOAD_ENGINEERING_MANAGER_TTLS_SUCCESS =
  'LOAD_ENGINEERING_MANAGER_TTLS_SUCCESS';
export const LOAD_ENGINEERING_MANAGER_TTLS_FAILURE =
  'LOAD_ENGINEERING_MANAGER_TTLS_FAILURE';
