export const FETCH_ENGINEER_REPORT_REQUEST = 'FETCH_ENGINEER_REPORT_REQUEST';
export const FETCH_ENGINEER_REPORT_SUCCESS = 'FETCH_ENGINEER_REPORT_SUCCESS';
export const FETCH_ENGINEER_REPORT_FAILURE = 'FETCH_ENGINEER_REPORT_FAILURE';
