export const LOAD_READ_NOTIFICATION_REQUEST = 'LOAD_READ_NOTIFICATION_REQUEST';
export const LOAD_READ_NOTIFICATION_SUCCESS = 'LOAD_READ_NOTIFICATION_SUCCESS';
export const LOAD_READ_NOTIFICATION_FAILURE = 'LOAD_READ_NOTIFICATION_FAILURE';
