export const LOAD_FELLOW_REQUEST = 'LOAD_FELLOW_REQUEST';
export const LOAD_FELLOW_SUCCESS = 'LOAD_FELLOW_SUCCESS';
export const LOAD_FELLOW_FAILURE = 'LOAD_FELLOW_FAILURE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const LOAD_FELLOW_PULSE_REQUEST = 'LOAD_FELLOW_PULSE_REQUEST';
export const LOAD_FELLOW_PULSE_SUCCESS = 'LOAD_FELLOW_PULSE_SUCCESS';
export const LOAD_FELLOW_PULSE_FAILURE = 'LOAD_FELLOW_PULSE_FAILURE';
export const LOAD_FELLOW_LMS_SUBMISSIONS_REQUEST =
  'LOAD_FELLOW_LMS_SUBMISSIONS_REQUEST';
export const LOAD_FELLOW_LMS_SUBMISSIONS_SUCCESS =
  'LOAD_FELLOW_LMS_SUBMISSIONS_SUCCESS';
export const LOAD_FELLOW_LMS_SUBMISSIONS_FAILURE =
  'LOAD_FELLOW_LMS_SUBMISSIONS_FAILURE';
