export const LOAD_FELLOW_COUNT_HISTORY_REQUEST =
  'LOAD_FELLOW_COUNT_HISTORY_REQUEST';
export const LOAD_FELLOW_COUNT_HISTORY_SUCCESS =
  'LOAD_FELLOW_COUNT_HISTORY_SUCCESS';
export const LOAD_FELLOW_COUNT_HISTORY_FAILURE =
  'LOAD_FELLOW_COUNT_HISTORY_FAILURE';
