export const LOAD_UNREAD_NOTIFICATION_REQUEST =
  'LOAD_UNREAD_NOTIFICATION_REQUEST';
export const LOAD_UNREAD_NOTIFICATION_SUCCESS =
  'LOAD_UNREAD_NOTIFICATION_SUCCESS';
export const LOAD_UNREAD_NOTIFICATION_FAILURE =
  'LOAD_UNREAD_NOTIFICATION_FAILURE';
