export const LOAD_FELLOW_REQUEST = 'LOAD_FELLOW_REQUEST';
export const LOAD_FELLOW_SUCCESS = 'LOAD_FELLOW_SUCCESS';
export const LOAD_FELLOW_FAILURE = 'LOAD_FELLOW_FAILURE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
