export const LOAD_FELLOW_LMS_RATINGS_REQUEST =
  'LOAD_FELLOW_LMS_RATINGS_REQUEST';
export const LOAD_FELLOW_LMS_RATINGS_SUCCESS =
  'LOAD_FELLOW_LMS_RATINGS_SUCCESS';
export const LOAD_FELLOW_LMS_RATINGS_FAILURE =
  'LOAD_FELLOW_LMS_RATINGS_FAILURE';
