export const LOAD_FELLOW_PROGRESS_FAILURE = 'LOAD_FELLOW_PROGRESS_FAILURE';
export const LOAD_FELLOW_PROGRESS_SUCCESS = 'LOAD_FELLOW_PROGRESS_SUCCESS';
export const LOAD_FELLOW_PROGRESS_REQUEST = 'LOAD_FELLOW_PROGRESS_REQUEST';
