export const FETCH_SUMMARY_SUCCESS = 'FETCH_SUMMARY_SUCCESS';
export const FETCH_SUMMARY_ERROR = 'FETCH_SUMMARY_ERROR';
export const FETCH_SUMMARY_REQUEST = 'FETCH_SUMMARY_REQUEST';
export const FETCH_TTLLF_SUMMARY_REQUEST = 'FETCH_TTLLF_SUMMARY_REQUEST';
export const FETCH_TTLLF_SUMMARY_ERROR = 'FETCH_TTLLF_SUMMARY_ERROR';
export const FETCH_TTLLF_SUMMARY_SUCCESS = 'FETCH_TTLLF_SUMMARY_SUCCESS';
