export const FETCH_ROLE_ACTIVE_ENGINEER_SUCCESS =
  'FETCH_ROLE_ACTIVE_ENGINEER_SUCCESS';
export const FETCH_ROLE_ACTIVE_ENGINEER_REQUEST =
  'FETCH_ROLE_ACTIVE_ENGINEER_REQUEST';
export const FETCH_ROLE_ACTIVE_ENGINEER_FAILURE =
  'FETCH_ROLE_ACTIVE_ENGINEER_FAILURE';
