export const FELLOW_FEEDBACK = 'FELLOW_FEEDBACK';
export const GET_FELLOW_PRE_PIP_FEEDBACK_REQUEST = 'GET_FELLOW_PRE_PIP_FEEDBACK_REQUEST';
export const GET_FELLOW_PRE_PIP_FEEDBACK_FAILURE = 'GET_FELLOW_PRE_PIP_FEEDBACK_FAILURE';
export const GET_FELLOW_PRE_PIP_FEEDBACK_SUCCESS = 'GET_FELLOW_PRE_PIP_FEEDBACK_SUCCESS';
export const GET_FELLOW_PIP_FEEDBACK_REQUEST = 'GET_FELLOW_PIP_FEEDBACK_REQUEST';
export const GET_FELLOW_PIP_FEEDBACK_SUCCESS = 'GET_FELLOW_PIP_FEEDBACK_SUCCESS';
export const GET_FELLOW_PIP_FEEDBACK_FAILURE = 'GET_FELLOW_PIP_FEEDBACK_FAILURE';