export const LOAD_LF_NOTIFICATION_REQUEST = 'LOAD_LF_NOTIFICATION_REQUEST';
export const LOAD_LF_NOTIFICATION_SUCCESS = 'LOAD_LF_NOTIFICATION_SUCCESS';
export const LOAD_LF_NOTIFICATION_FAILURE = 'LOAD_LF_NOTIFICATION_FAILURE';
