export const LOAD_MANAGER_REQUEST = 'LOAD_MANAGER_REQUEST';
export const LOAD_MANAGER_SUCCESS = 'LOAD_MANAGER_SUCCESS';
export const LOAD_MANAGER_FAILURE = 'LOAD_MANAGER_FAILURE';

export const MANAGER_PROFILE_DATA_REQUEST = 'MANAGER_PROFILE_DATA_REQUEST';
export const MANAGER_PROFILE_DATA_SUCCESS = 'MANAGER_PROFILE_DATA_SUCCESS';
export const MANAGER_PROFILE_DATA_FAILURE = 'MANAGER_PROFILE_DATA_FAILURE';
