export const LOAD_MANAGER_READ_NOTIFICATION_REQUEST =
  'LOAD_MANAGER_READ_NOTIFICATION_REQUEST';
export const LOAD_MANAGER_READ_NOTIFICATION_SUCCESS =
  'LOAD_MANAGER_READ_NOTIFICATION_SUCCESS';
export const LOAD_MANAGER_READ_NOTIFICATION_FAILURE =
  'LOAD_MANAGER_READ_NOTIFICATION_FAILURE';
