export const LOAD_OPS_SUMMARY_REQUEST = 'LOAD_OPS_SUMMARY_REQUEST';
export const LOAD_OPS_SUMMARY_SUCCESS = 'LOAD_OPS_SUMMARY_SUCCESS';
export const LOAD_OPS_SUMMARY_FAILURE = 'LOAD_OPS_SUMMARY_FAILURE';

export const MANAGER_PROFILE_DATA_REQUEST = 'MANAGER_PROFILE_DATA_REQUEST';
export const MANAGER_PROFILE_DATA_SUCCESS = 'MANAGER_PROFILE_DATA_SUCCESS';
export const MANAGER_PROFILE_DATA_FAILURE = 'MANAGER_PROFILE_DATA_FAILURE';
