export const LOAD_MANAGERFELLOWS_REQUEST = 'LOAD_MANAGERFELLOWS_REQUEST';
export const LOAD_MANAGERFELLOWS_SUCCESS = 'LOAD_MANAGERFELLOWS_SUCCESS';
export const LOAD_MANAGERFELLOWS_FAILURE = 'LOAD_MANAGERFELLOWS_FAILURE';
