export const LOAD_MANAGER_FELLOWS_SUMMARY_REQUEST =
  'LOAD_MANAGER_FELLOWS_SUMMARY_REQUEST';
export const LOAD_MANAGER_FELLOWS_SUMMARY_SUCCESS =
  'LOAD_MANAGER_FELLOWS_SUMMARY_SUCCESS';
export const LOAD_MANAGER_FELLOWS_SUMMARY_FAILURE =
  'LOAD_MANAGER_FELLOWS_SUMMARY_FAILURE';
