export const EDIT_CERTIFICATION_SUCCESS = 'EDIT_CERTIFICATION_SUCCESS';
export const EDIT_CERTIFICATION_FAILURE = 'EDIT_CERTIFICATION_FAILURE';
export const EDIT_CERTIFICATION_REQUEST = 'EDIT_CERTIFICATION_REQUEST';
