export const FETCH_PERFORMANCE_DATA_REQUEST = 'FETCH_PERFORMANCE_DATA_REQUEST';
export const FETCH_PERFORMANCE_DATA_SUCCESS = 'FETCH_PERFORMANCE_DATA_SUCCESS';
export const FETCH_PERFORMANCE_DATA_FAILURE = 'FETCH_PERFORMANCE_DATA_FAILURE';
