export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

export const EDIT_PROJECT_REQUEST = 'EDIT_PROJECT_REQUEST';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';
export const EDIT_PROJECT_FAILURE = 'EDIT_PROJECT_FAILURE';

export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const GET_SINGLE_PROJECT_REQUEST = 'GET_SINGLE_PROJECT_REQUEST';
export const GET_SINGLE_PROJECT_SUCCESS = 'GET_SINGLE_PROJECT_SUCCESS';
export const GET_SINGLE_PROJECT_FAILURE = 'GET_SINGLE_PROJECT_FAILURE';

export const SET_PROJECT_DELETE_TARGET = 'SET_PROJECT_DELETE_TARGET';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

export const TOGGLE_PROJECT_MANAGER_MODAL = 'TOGGLE_PROJECT_MANAGER_MODAL';
export const ADD_PROJECT_MANAGER = 'ADD_PROJECT_MANAGER';
export const ADD_PROJECT_TECHNOLOGY = 'ADD_PROJECT_TECHNOLOGY';

export const RETRIEVE_PROJECT_MANAGERS_REQUEST =
  'RETRIEVE_PROJECT_MANAGERS_REQUEST';
export const RETRIEVE_PROJECT_MANAGERS_SUCCESS =
  'RETRIEVE_PROJECT_MANAGERS_SUCCESS';
export const RETRIEVE_PROJECT_MANAGERS_FAILURE =
  'RETRIEVE_PROJECT_MANAGERS_FAILURE';

export const RETRIEVE_PROJECT_TECH_REQUEST = 'RETRIEVE_PROJECT_TECH_REQUEST';
export const RETRIEVE_PROJECT_TECH_SUCCESS = 'RETRIEVE_PROJECT_TECH_SUCCESS';
export const RETRIEVE_PROJECT_TECH_FAILURE = 'RETRIEVE_PROJECT_TECH_FAILURE';

export const FETCH_SLACK_CHANNELS_REQUEST = 'FETCH_SLACK_CHANNELS_REQUEST';
export const FETCH_SLACK_CHANNELS_SUCCESS = 'FETCH_SLACK_CHANNELS_SUCCESS';
export const FETCH_SLACK_CHANNELS_FAILURE = 'FETCH_SLACK_CHANNELS_FAILURE';

export const CREATE_PROJECT_VACANCIES_REQUEST =
  'CREATE_PROJECT_VACANCIES_REQUEST';
export const CREATE_PROJECT_VACANCIES_SUCCESS =
  'CREATE_PROJECT_VACANCIES_SUCCESS';
export const CREATE_PROJECT_VACANCIES_FAILURE =
  'CREATE_PROJECT_VACANCIES_FAILURE';

export const GET_ALL_VACANCIES_REQUEST = 'GET_ALL_VACANCIES_REQUEST';
export const GET_ALL_VACANCIES_SUCCESS = 'GET_ALL_VACANCIES_SUCCESS';
export const GET_ALL_VACANCIES_FAILURE = 'GET_ALL_VACANCIES_FAILURE';

export const EDIT_PROJECT_VACANCIES_REQUEST = 'EDIT_PROJECT_VACANCIES_REQUEST';
export const EDIT_PROJECT_VACANCIES_SUCCESS = 'EDIT_PROJECT_VACANCIES_SUCCESS';
export const EDIT_PROJECT_VACANCIES_FAILURE = 'EDIT_PROJECT_VACANCIES_FAILURE';

export const DELETE_PROJECT_VACANCIES_REQUEST =
  'DELETE_PROJECT_VACANCIES_REQUEST';
export const DELETE_PROJECT_VACANCIES_SUCCESS =
  'DELETE_PROJECT_VACANCIES_SUCCESS';
export const DELETE_PROJECT_VACANCIES_FAILURE =
  'DELETE_PROJECT_VACANCIES_FAILURE';

export const SET_PROJECT_VACANCIES_ON_FOCUS = 'SET_PROJECT_VACANCIES_ON_FOCUS';
export const ADD_NEW_VACANCIES_TO_PROJECT_VACANCIES =
  'ADD_NEW_VACANCIES_TO_PROJECT_VACANCIES';
export const UPDATE_PROJECT_VACANCIES_ON_FOCUS =
  'UPDATE_PROJECT_VACANCIES_ON_FOCUS';
export const REMOVE_PROJECT_VACANCIES_ON_FOCUS =
  'REMOVE_PROJECT_VACANCIES_ON_FOCUS';

export const GET_ALL_VACANCIES_WITH_NO_CYCLEID_REQUEST =
  'GET_ALL_VACANCIES_WITH_NO_CYCLEID_REQUEST';
export const GET_ALL_VACANCIES_WITH_NO_CYCLEID_SUCCESS =
  'GET_ALL_VACANCIES_WITH_NO_CYCLEID_SUCCESS';
export const GET_ALL_VACANCIES_WITH_NO_CYCLEID_FAILURE =
  'GET_ALL_VACANCIES_WITH_NO_CYCLEID_FAILURE';
