export const LOAD_SIMULATIONS_LEAD_LF_REQUEST =
  'LOAD_SIMULATIONS_LEAD_LF_REQUEST';
export const LOAD_SIMULATIONS_LEAD_LF_SUCCESS =
  'LOAD_SIMULATIONS_LEAD_LF_SUCCESS';
export const LOAD_SIMULATIONS_LEAD_LF_FAILURE =
  'LOAD_SIMULATIONS_LEAD_LF_FAILURE';
