export const GET_TEAM_MEMBERS_REQUEST = 'GET_TEAM_MEMBERS_REQUEST';
export const GET_TEAM_MEMBERS_SUCCESS = 'GET_TEAM_MEMBERS_SUCCESS';
export const GET_TEAM_MEMBERS_FAILURE = 'GET_TEAM_MEMBERS_FAILURE';

export const ROLL_OFF_TEAM_MEMBER_REQUEST = 'ROLL_OFF_TEAM_MEMBER_REQUEST';
export const ROLL_OFF_TEAM_MEMBER_SUCCESS = 'ROLL_OFF_TEAM_MEMBER_SUCCESS';
export const ROLL_OFF_TEAM_MEMBER_FAILURE = 'ROLL_OFF_TEAM_MEMBER_FAILURE';
export const REMOVE_ENGINEER_CARD = 'REMOVE_ENGINEER_CARD';
