export const LOAD_TTL_NOTIFICATION_REQUEST = 'LOAD_TTL_NOTIFICATION_REQUEST';
export const LOAD_TTL_NOTIFICATION_SUCCESS = 'LOAD_TTL_NOTIFICATION_SUCCESS';
export const LOAD_TTL_NOTIFICATION_FAILURE = 'LOAD_TTL_NOTIFICATION_FAILURE';
