export const LOAD_TTLS_FAILURE = 'LOAD_TTLS_FAILURE';
export const LOAD_TTLS_SUCCESS = 'LOAD_TTLS_SUCCESS';
export const LOAD_TTLS_REQUEST = 'LOAD_TTLS_REQUEST';
export const TTL_PROJECTS_REQUEST = 'TTL_PROJECTS_REQUEST';
export const TTL_PROJECTS_SUCCESS = 'TTL_PROJECTS_SUCCESS';
export const TTL_PROJECTS_FAILURE = 'TTL_PROJECTS_FAILURE';
